CREATE TABLE [TOURNAMENT_TRACKER].[MatchupEntries](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[MatchupId] [int] NOT NULL,
	[ParentMatchupId] [int] NULL,
	[TeamCompetingId] [int] NULL,
	[Score] [float] NULL,
 CONSTRAINT [PK_MatchupEntries] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [TOURNAMENT_TRACKER].[MatchupEntries]  WITH CHECK ADD  CONSTRAINT [FK_MatchupEntries_Matchups] FOREIGN KEY([MatchupId])
REFERENCES [TOURNAMENT_TRACKER].[Matchups] ([Id])
GO

ALTER TABLE [TOURNAMENT_TRACKER].[MatchupEntries] CHECK CONSTRAINT [FK_MatchupEntries_Matchups]
GO

ALTER TABLE [TOURNAMENT_TRACKER].[MatchupEntries]  WITH CHECK ADD  CONSTRAINT [FK_MatchupEntries_Matchups1] FOREIGN KEY([ParentMatchupId])
REFERENCES [TOURNAMENT_TRACKER].[Matchups] ([Id])
GO

ALTER TABLE [TOURNAMENT_TRACKER].[MatchupEntries] CHECK CONSTRAINT [FK_MatchupEntries_Matchups1]
GO

ALTER TABLE [TOURNAMENT_TRACKER].[MatchupEntries]  WITH CHECK ADD  CONSTRAINT [FK_MatchupEntries_Teams] FOREIGN KEY([TeamCompetingId])
REFERENCES [TOURNAMENT_TRACKER].[Teams] ([Id])
GO

ALTER TABLE [TOURNAMENT_TRACKER].[MatchupEntries] CHECK CONSTRAINT [FK_MatchupEntries_Teams]
GO
