CREATE TABLE [TOURNAMENT_TRACKER].[Matchups](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[WinnerId] [int] NULL,
	[MatchupRound] [int] NOT NULL,
	[TournamentId] [int] NOT NULL,
 CONSTRAINT [PK_Matchups] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [TOURNAMENT_TRACKER].[Matchups]  WITH CHECK ADD  CONSTRAINT [FK_Matchups_Teams] FOREIGN KEY([WinnerId])
REFERENCES [TOURNAMENT_TRACKER].[Teams] ([Id])
GO

ALTER TABLE [TOURNAMENT_TRACKER].[Matchups] CHECK CONSTRAINT [FK_Matchups_Teams]
GO

ALTER TABLE [TOURNAMENT_TRACKER].[Matchups]  WITH CHECK ADD  CONSTRAINT [FK_Matchups_Tournaments] FOREIGN KEY([TournamentId])
REFERENCES [TOURNAMENT_TRACKER].[Tournaments] ([Id])
GO

ALTER TABLE [TOURNAMENT_TRACKER].[Matchups] CHECK CONSTRAINT [FK_Matchups_Tournaments]
GO


