
CREATE TABLE [TOURNAMENT_TRACKER].[TeamMembers](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TeamId] [int] NOT NULL,
	[PersonId] [int] NOT NULL,
 CONSTRAINT [PK_TeamMembers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [TOURNAMENT_TRACKER].[TeamMembers]  WITH CHECK ADD  CONSTRAINT [FK_TeamMembers_People] FOREIGN KEY([PersonId])
REFERENCES [TOURNAMENT_TRACKER].[People] ([Id])
GO

ALTER TABLE [TOURNAMENT_TRACKER].[TeamMembers] CHECK CONSTRAINT [FK_TeamMembers_People]
GO

ALTER TABLE [TOURNAMENT_TRACKER].[TeamMembers]  WITH CHECK ADD  CONSTRAINT [FK_TeamMembers_Teams] FOREIGN KEY([TeamId])
REFERENCES [TOURNAMENT_TRACKER].[Teams] ([Id])
GO

ALTER TABLE [TOURNAMENT_TRACKER].[TeamMembers] CHECK CONSTRAINT [FK_TeamMembers_Teams]
GO


