CREATE TABLE [TOURNAMENT_TRACKER].[TournamentPrizes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TournamentId] [int] NOT NULL,
	[PrizeId] [int] NOT NULL,
 CONSTRAINT [PK_TournamentPrizes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [TOURNAMENT_TRACKER].[TournamentPrizes]  WITH CHECK ADD  CONSTRAINT [FK_TournamentPrizes_Prizes] FOREIGN KEY([PrizeId])
REFERENCES [TOURNAMENT_TRACKER].[Prizes] ([Id])
GO

ALTER TABLE [TOURNAMENT_TRACKER].[TournamentPrizes] CHECK CONSTRAINT [FK_TournamentPrizes_Prizes]
GO

ALTER TABLE [TOURNAMENT_TRACKER].[TournamentPrizes]  WITH CHECK ADD  CONSTRAINT [FK_TournamentPrizes_Tournaments] FOREIGN KEY([TournamentId])
REFERENCES [TOURNAMENT_TRACKER].[Tournaments] ([Id])
GO

ALTER TABLE [TOURNAMENT_TRACKER].[TournamentPrizes] CHECK CONSTRAINT [FK_TournamentPrizes_Tournaments]
GO


